import Link from 'next/link'

export const dynamic = 'force-dynamic'

// CXO Suite is a separate brand from Virtual Closer — see lib/brand.ts.
// Middleware rewrites `/` on suitecxo.com to this route, so this is the
// public landing page that executives see before signing in.
//
// Palette is hard-coded (not from CSS vars) because the page is locked to
// the CXO identity regardless of any future global theming changes.
// Names kept for git-diff clarity; values were swapped from a brown/mocha
// system to a charcoal + cream-vanilla system.
const ESPRESSO = '#2A2A2A'   // charcoal (primary ink / accent)
const ALMOND = '#C9C2B0'     // warm vanilla (highlight accent)
const SAND = '#D6D0BF'       // light vanilla (secondary accent)
const BEIGE = '#EFEAE0'      // cream-vanilla (secondary surface)
const IVORY = '#FAF7F0'      // vanilla (page canvas)
const INK_MUTED = '#555555'  // mid charcoal (muted text)

const LOGO_SRC =
  'https://ndschjbuyjmxtzqyjgyi.supabase.co/storage/v1/object/public/logo%20filess/cxo%20logo/CXO%20Suite.png'

export default function CxoMarketingPage() {
  return (
    <main
      style={{
        // Canvas comes from the .cxo-shell wrapper in app/layout.tsx so
        // we render transparent here.
        color: ESPRESSO,
        // Padding shrinks on small screens so the content has real breathing
        // room on mobile rather than getting pinched against viewport edges.
        padding: 'clamp(2rem, 5vw, 3.5rem) clamp(1rem, 4vw, 2.5rem) clamp(4rem, 8vw, 6rem)',
        fontFamily: '"IBM Plex Sans", "Inter", "Avenir Next", system-ui, sans-serif',
      }}
    >
      <div style={{ maxWidth: 1120, margin: '0 auto' }}>

        {/* ── Hero ──────────────────────────────────────────────────── */}
        <header style={{ display: 'grid', gap: '1.3rem', padding: 'clamp(1.5rem, 5vw, 3rem) 0 clamp(2.5rem, 6vw, 4rem)', textAlign: 'center' }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={LOGO_SRC}
            alt="CXO Suite"
            style={{
              display: 'block',
              margin: '0 auto 0.25rem',
              height: 'clamp(96px, 18vw, 160px)',
              width: 'auto',
              maxWidth: '90%',
            }}
          />
          <Eyebrow>The Executive Operating System</Eyebrow>
          <Display>
            <span style={{ whiteSpace: 'nowrap' }}>Custom built &amp; integrated</span>
            <br />
            <em style={{ color: ALMOND, fontStyle: 'italic', fontWeight: 400 }}>
              operations dashboard for executives.
            </em>
          </Display>
          <p
            style={{
              fontSize: '1.18rem',
              maxWidth: 720,
              margin: '0.5rem auto 0',
              lineHeight: 1.65,
              color: INK_MUTED,
            }}
          >
            CXO Suite pulls live performance from your reps, runs your AI agents,
            organizes your calendar and inbox, and gives your chief of staff a seat
            at the controls — so you stop chasing updates and start running the company.
          </p>
          <div
            style={{
              display: 'flex',
              gap: '0.8rem',
              justifyContent: 'center',
              marginTop: '1rem',
              flexWrap: 'wrap',
            }}
          >
            <PrimaryButton href="/demo">Request access</PrimaryButton>
            <GhostButton href="/login">Sign in</GhostButton>
          </div>
        </header>

        {/* ── Section 1: Live team intelligence ───────────────────── */}
        <Section
          eyebrow="Real-time KPI dashboard"
          title="Live pipeline, revenue, and per-rep performance on one screen."
          body="Every meeting, deal, dollar, and calendar block from your operation rolls up here in real time, pulled directly from the tools your team already uses. KPIs aren't a Monday email — they're the screen you keep open."
          highlights={[
            'Live pipeline value, revenue tracking, and performance by team member',
            'External tools (HubSpot, GHL, Airtable, Salesforce, Pipedrive, your calendar, your inbox) unified into one feed',
            'Weekly board-ready briefs auto-generated by your AI Business Analyst',
            'Drill into any person on your team — their day, their open work, their calendar load',
          ]}
        />

        {/* ── Section 2: AI executive team ─────────────────────────── */}
        <Section
          eyebrow="Four AI executives, pre-built"
          title="Chief of Staff, Ops Manager, Business Analyst, and Briefing Officer on staff."
          body="Most founders we work with have a Chief of Staff role on a sticky note. CXO Suite fills it — and three more — with AI agents that triage your inbox, organize your brain-dumps, roll up live KPIs, and turn every meeting into action items. Same engine that runs in seven-figure operations, deployed in an afternoon."
          highlights={[
            'AI Chief of Staff — triages your inbox, drafts replies in your voice, protects your calendar, prepares your morning brief',
            'AI Operations Manager — captures everything you brain-dump, organizes it into tasks, deals, and follow-ups, then tracks completion',
            'AI Business Analyst — rolls up live KPIs across every tool your team uses (HubSpot, GHL, Airtable, Salesforce), surfaces what changed, ships a board-ready brief every week',
            'AI Briefing Officer — every call, meeting, and recording becomes a transcript, a summary, and a list of action items overnight — never lose a "what did they say?" again',
          ]}
        />

        {/* ── Section 3: Comms + organization ─────────────────────── */}
        <Section
          eyebrow="Private Telegram channels for leadership"
          title="Owners Room + Leadership Channel with AI task assignment."
          body="Two private Telegram surfaces only execs and leadership see — no rep clutter, no marketing noise. Brain-dump any text, voice note, or photo and the AI Operations Manager turns it into tasks, deals, or follow-ups assigned to a named person with completion tracking in the dashboard."
          highlights={[
            'Private Owners Room + Leadership Channel — no rep clutter, no marketing noise',
            'Brain-dump anything (text, voice, photo) — your AI Operations Manager organizes it into tasks, deals, follow-ups',
            'Assign work to a specific person via Telegram; track completion in the dashboard',
            'Morning brief delivered to your DM every day — what shifted overnight, what needs you today',
          ]}
        />

        {/* ── Section 4: Assistant + chief of staff ──────────────── */}
        <Section
          eyebrow="Multi-seat admin + audit trail"
          title="Invite an EA in one click with full admin access and per-action audit logs."
          body="One click adds your assistant to your suite — calendar, inbox, reports, comms, the same views you have. Every action they take is logged so you always know who did what, when. Add or remove assistants from /dashboard/settings; support multiple assistants if your operation calls for it."
          highlights={[
            'Add or remove an assistant from /dashboard/settings in under a minute',
            'Your assistant sees what you see and acts as you when needed',
            'Audit trail on every action — you always know who did what, when',
            'Manage multiple assistants if your operation calls for it',
          ]}
        />

        {/* ── Section 5: Organization + recall ────────────────────── */}
        <Section
          eyebrow="Calendar, inbox, and meeting recall"
          title="Gmail triage, calendar-aware AI drafts, and overnight meeting summaries."
          body="One screen replaces ten tools. The AI Chief of Staff drafts Gmail replies that respect your real calendar availability. Fathom, Plaud, and Cal.com meetings auto-save with summaries and next steps. PDFs and briefs generate from underlying meeting + deal context. Task reminders fire on Telegram, not in another app you forget about."
          highlights={[
            'Gmail triage with one-click AI drafts that respect your real calendar',
            'Fathom, Plaud, and Cal.com meetings auto-saved with summaries and next steps',
            'PDF briefs and proposals generated from the underlying meeting + deal context',
            'Task reminders that fire on Telegram, not in another app you forget about',
          ]}
        />

        {/* ── Closing CTA ─────────────────────────────────────────── */}
        <footer
          style={{
            marginTop: 'clamp(3rem, 8vw, 5rem)',
            padding: 'clamp(2.5rem, 6vw, 3.5rem) clamp(1.25rem, 4vw, 2rem)',
            background: BEIGE,
            borderRadius: 28,
            textAlign: 'center',
          }}
        >
          <Eyebrow>By invitation · Founding cohort</Eyebrow>
          <Display style={{ fontSize: 'clamp(1.9rem, 3.6vw, 2.8rem)', margin: '0.6rem 0 1rem' }}>
            Built first for one executive.<br />Now scaling to ten.
          </Display>
          <p style={{ maxWidth: 580, margin: '0 auto 1.6rem', color: INK_MUTED, lineHeight: 1.65 }}>
            CXO Suite is the productized version of the operating system we built
            for one founder running a wellness business. Same AI workforce, same
            comms layer, same data pipes — yours to deploy.
          </p>
          <PrimaryButton href="/demo">Request access</PrimaryButton>
        </footer>

        <p
          style={{
            marginTop: '3rem',
            textAlign: 'center',
            fontSize: 12,
            color: SAND,
            letterSpacing: '0.05em',
          }}
        >
          © {new Date().getFullYear()} CXO Suite · suitecxo.com
        </p>
      </div>
    </main>
  )
}

// ── Sub-components ────────────────────────────────────────────────

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: 12,
        letterSpacing: '0.22em',
        textTransform: 'uppercase',
        color: ALMOND,
        fontWeight: 700,
        margin: 0,
      }}
    >
      {children}
    </p>
  )
}

function Display({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return (
    <h1
      style={{
        fontSize: 'clamp(2.4rem, 5.4vw, 4.2rem)',
        fontFamily: '"Cormorant Garamond", "Playfair Display", Georgia, serif',
        fontWeight: 500,
        lineHeight: 1.08,
        letterSpacing: '-0.02em',
        margin: 0,
        color: ESPRESSO,
        ...style,
      }}
    >
      {children}
    </h1>
  )
}

function PrimaryButton({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <Link
      href={href}
      style={{
        background: ESPRESSO,
        color: IVORY,
        padding: '0.95rem 1.8rem',
        borderRadius: 999,
        fontWeight: 600,
        fontSize: 15,
        textDecoration: 'none',
        letterSpacing: '0.02em',
        display: 'inline-block',
      }}
    >
      {children}
    </Link>
  )
}

function GhostButton({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <Link
      href={href}
      style={{
        background: 'transparent',
        color: ESPRESSO,
        padding: '0.95rem 1.8rem',
        borderRadius: 999,
        fontWeight: 600,
        fontSize: 15,
        textDecoration: 'none',
        letterSpacing: '0.02em',
        border: `1.5px solid ${ESPRESSO}`,
        display: 'inline-block',
      }}
    >
      {children}
    </Link>
  )
}

function Section({
  eyebrow,
  title,
  body,
  highlights,
}: {
  eyebrow: string
  title: string
  body: string
  highlights: string[]
}) {
  return (
    <details
      className="cxo-section"
      style={{
        marginTop: 'clamp(1.1rem, 3vw, 2rem)',
        background: '#FFFFFF',
        borderRadius: 22,
        border: `1px solid ${BEIGE}`,
        overflow: 'hidden',
      }}
    >
      <summary
        style={{
          listStyle: 'none',
          cursor: 'pointer',
          padding: 'clamp(1.4rem, 4vw, 2rem) clamp(1.4rem, 4vw, 2rem) clamp(1.2rem, 3.5vw, 1.6rem)',
          display: 'grid',
          gap: '0.7rem',
          userSelect: 'none',
        }}
      >
        <p
          style={{
            fontSize: 12,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: ALMOND,
            fontWeight: 700,
            margin: 0,
          }}
        >
          {eyebrow}
        </p>
        <h2
          style={{
            fontFamily: '"Cormorant Garamond", "Playfair Display", Georgia, serif',
            fontWeight: 500,
            fontSize: 'clamp(1.3rem, 2.6vw, 2rem)',
            margin: 0,
            lineHeight: 1.22,
            color: ESPRESSO,
            letterSpacing: '-0.01em',
          }}
        >
          {title}
        </h2>
        <p
          style={{
            color: INK_MUTED,
            lineHeight: 1.65,
            margin: 0,
            fontSize: 'clamp(0.94rem, 1.5vw, 1.02rem)',
            maxWidth: 740,
          }}
        >
          {body}
        </p>
        <div
          className="cxo-section-more"
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            justifyContent: 'flex-end',
            marginTop: '0.25rem',
            fontSize: 12,
            fontWeight: 600,
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: ALMOND,
          }}
        >
          <span className="cxo-section-more-label">What&apos;s inside</span>
          <span aria-hidden className="cxo-chevron" style={{ transition: 'transform 180ms ease', fontSize: '0.7rem' }}>
            ▼
          </span>
        </div>
      </summary>
      <div
        style={{
          padding: '0 clamp(1.4rem, 4vw, 2rem) clamp(1.6rem, 4.5vw, 2.2rem)',
          display: 'grid',
          gap: '1rem',
          borderTop: `1px dashed ${BEIGE}`,
          paddingTop: '1.2rem',
        }}
      >
        <ul className="cxo-highlight-grid">
          {highlights.map((h, i) => (
            <li
              key={i}
              style={{
                display: 'flex',
                gap: 10,
                padding: '0.6rem 0.9rem',
                background: IVORY,
                borderRadius: 12,
                fontSize: '0.93rem',
                color: ESPRESSO,
                lineHeight: 1.45,
                border: `1px solid ${BEIGE}`,
              }}
            >
              <span style={{ color: ALMOND, fontWeight: 800, flexShrink: 0 }}>—</span>
              <span>{h}</span>
            </li>
          ))}
        </ul>
      </div>
    </details>
  )
}
